version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=car_rent_jizy
      - POSTGRES_USER=car_rent_jizy_user
      - POSTGRES_PASSWORD=ewW8CXozwK7g38jkY05V4NcWQgA0ha3d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
